version: '2'
services:
  mysql-database:
    image: mysql
    ports:
      - "3344:3306"
    restart: always
    environment:
      MYSQL_DATABASE: 数据库名  // 这里docker 在启动的时候，会自动创建该数据库，不需要手动去创建
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 数据库密码
